#!/usr/bin/env bash

source logr.sh

# whether to open the SVG on completion in your browser
# - allowed values:
#   - "true" to enable this feature
#   - "false" disable this feature
declare -r PREVIEW=false

# browser for preview
# - allowed values:
#   - empty (e.g. '' or "") to use default browser
#   - app ID (e.g. "com.mozilla.firefox")
#   - app name (e.g. "Google Chrome", "Firefox")
declare -r BROWSER=''

# where to store artifacts
declare -r BUILD_DIR=build/rec/authoring

# where to store the rec file
declare -r REC_FILE="$BUILD_DIR/foo.rec"

# contents of the rec file
# shellcheck disable=SC2155
declare -r RECORDING=$(
  # language=sh
  cat <<'REC-FILE'

rec "Hello World"

REC-FILE
)

### BETTER NOT TOUCH BELOW CODE ###

# create rec file and convert it
mkdir -p "$BUILD_DIR"
echo "$RECORDING" >"$REC_FILE"
TESTING=1 ./recordr \
 --rec-dir "${REC_FILE%/*}" \
 --build-dir "$BUILD_DIR" \
 --restart-delay 1 \
 --out-dir "$BUILD_DIR" \
 "${REC_FILE##*/}"

# if preview is enabled, continue; otherwise, stop here
[ "${PREVIEW}" = true ] || exit 0

# open SVG in browser / refresh browser
declare abs_dir && abs_dir=$(cd "${REC_FILE%/*}" && pwd)
declare svg_file="${REC_FILE%.*}.svg"
./browsr reload "file://$abs_dir/${svg_file##*/}" ${BROWSER+$BROWSER}
