#!/usr/bin/env bash

set -euo pipefail

DOCKER_BUILDKIT=1 \
DOCKER_SCAN_SUGGEST=false \
docker build \
  --build-arg APP_HOME="/home/john" \
  --build-arg TZ="$(date +"%Z")" \
  --build-arg PUID="$(id -u)" \
  --build-arg PGID="$(id -g)" \
  --tag bkahlert/recordr \
  . && \
docker run -it --rm --name "recordr-$(head /dev/urandom | LC_ALL=C.UTF-8 tr -dc A-Za-z0-9 | head -c 3)" \
  -e TZ="$(date +"%Z")" \
  -e PUID="$(id -u)" \
  -e PGID="$(id -g)" \
  -e NODE_OPTIONS="--max-old-space-size=16384" \
  -e TERM="$TERM" \
  -v "$PWD":"$PWD" \
  -w "$PWD" \
  bkahlert/recordr
