name: docs

on: [push,workflow_dispatch]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:

      - name: Print updated SVG files
        run: |
          echo "${{ env.GITHUB_WORKFLOW }}(docs): update"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Convert terminal sessions to SVG
        id: recordr
        uses: ./
        with:
          files: rec/hello-world.rec

#      - name: Print updated SVG files
#        run: |
#          echo "${{ steps.recordr.outputs.markdown }}"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        if: startsWith(github.ref, 'refs/heads/')
        with:
          commit-message: |
            ${{ github.workflow }}(docs): update ${{ steps.recordr.outputs.file-list }}
          title: |
            ${{ github.workflow }}(docs): update ${{ steps.recordr.outputs.file-list }}
          body: |
            Updates ${{ steps.recordr.outputs.file-list }}
            ${{ steps.recordr.outputs.markdown }}
          labels: recordr,docs,rec
          branch: ${{ github.ref_name }}--docs
